steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Use Node 16"
  - script: |
      npm install -g @microsoft/rush  
    displayName: "Install Rush"
  - script: |
      rush update
      rush build
    displayName: "Build"
