parameters:
  name: ""
  tag: ""

jobs:
  - job: ${{ parameters.name }}
    variables:
      - template: globals.yml
    steps:
      - template: build.yml
      - script: cd $(Build.SourcesDirectory)/packages/autorest && npm run clone:specs
        displayName: "Clone Specs Repository"

      - script: cd $(Build.SourcesDirectory)/packages/autorest && npm run smoke-test -- --tag=${{ parameters.tag }}
        displayName: "Run Smoke Tests"

      - script: cd $(Build.SourcesDirectory)/packages/autorest && npm run check:tree
        displayName: "Check git Tree"
